version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - DATABASE_PATH=/app/data/conversations.db
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - app_data:/app/data
      - ./.env.production:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    # Use host network for Ollama access if running locally
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  app_data:
    driver: local
