version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - DATABASE_PATH=/app/data/conversations.db
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
      - .:/app  # Mount source code for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Use host network for Ollama access if running locally
    extra_hosts:
      - "host.docker.internal:host-gateway"
